spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  rabbitmq:
    port: 5672
    host: 52.78.128.39
    username: admin
    password: admin
    virtual-host: /



  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
springdoc:
  swagger-ui:
    path: /api-test

rabbitmq:
  exchange: test.exchange
  keroro:
    binding-key: keroro
  geroro:
    binding-key: geroro
  garuru:
    binding-key: garuru